#! /bin/bash

#Create and run a docker container
docker run -d --restart=always --name ngnix-app -p 80:80 nginx

#Start Kube Pod
kubectl run --image=nginx nginx-app --port=80

#Expose via a service
kubectl expose deployment nginx-app --port=80 --name=nginx-service
